name: ForexPro

services:
  frontend:
    build: ./client
    env_file: ./client/.env
    ports:
      - "3000:3000"
  
  backend:
    build: ./server
    env_file: ./server/.env
    ports:
      - "3001:3001"
    depends_on:
      - postgres
      - rabbitmq
  
  postgres:
    image: postgres
    volumes:
      - ./data:/var/lib/postgresql
    env_file: ./server/.env
    ports:
      - "5433:5432"
  
  rabbitmq:
    image: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"