version: '3'
services:
  web:
    container_name: "web"
    build:
      context: ./client
      dockerfile: ./Dockerfile.test
    depends_on:
      - api
    volumes:
      - ./client:/app
  api:
    container_name: "api"
    build:
      context: ./server
      dockerfile: ./Dockerfile.test
    volumes:
      - ./server/src:/app/src


