version: '3'
services:
  web:
    container_name: "web"
    build: ./client
    ports:
      - "8080:3000"
    depends_on:
      - api
    volumes:
      - ./client:/app
  api:
    container_name: "api"
    build: ./server
    ports:
      - "3001:3000"
    depends_on:
      - redis
      - postgres
    volumes:
      - ./server/src:/app/src
    stdin_open: true 
    tty: true
  postgres:
    container_name: postgres
    image: postgres:alpine
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: forex-pro
    volumes:
      - postgresDB:/var/lib/postgresql/data
  redis:
    container_name: "redis"
    restart: always
    image: "redis:alpine"
    volumes:
      - redisDB:/data
volumes:
  postgresDB:
  redisDB:


