spring:
  datasource:
    url: jdbc:postgresql://${PG_HOSTNAME}:5432/forexpro
    username: ${PG_USER}
    password: ${PG_PASSWORD}

  rabbitmq:
    host: ${RABBIT_MQ_HOSTNAME}
    port: 5672
    username: ${RABBIT_MQ_USER}
    password: ${RABBIT_MQ_PASSWORD}
    virtual-host: ${RABBIT_MQ_USER}

  application:
    name: ForexPro

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

server:
  port: 3001

jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000 # 1 Hour

forex-api:
  url: wss://quote.alltick.io/quote-b-ws-api
